name: Build and Deploy to Nexus

on:
    repository_dispatch:
        types: [dispatch-event]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'adopt'
                cache: maven
            - name: Update joda-time version
              run: mvn versions:set-property -Dproperty=JODAVERSION -DnewVersion=${{ github.event.client_payload.JODA_VERSION }}
            
            - name: get spring-petclinic version
              run: echo "SPRINGVERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
            
            - name: Increment version
              run: |
                IFS='.' read -ra VERSION_PARTS <<< "${{ env.SPRINGVERSION }}"
                ((VERSION_PARTS[2]++))
                NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
                echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            - name: update spring-petclinic version
              run: mvn versions:set-property -Dproperty=SPRINGVERSION -DnewVersion=${{ env.NEW_VERSION }}
            
            - name: Build with Maven and Deploy
              run: mvn deploy --settings settings.xml
              env:
                NEXUS_USER: ${{ secrets.NEXUS_USER }}
                NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
                DISTRIBUTION_URL: ${{ secrets.DISTRIBUTION_URL }}